version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ticket_sales_db
      POSTGRES_USER: ticket_sales_user
      POSTGRES_PASSWORD: ticket_sales_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: ticket_sales.settings
      POSTGRES_DB: ticket_sales_db
      POSTGRES_USER: ticket_sales_user
      POSTGRES_PASSWORD: ticket_sales_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data: